/* v25: decoded, local audio recordings only. No generated tones/noise. */
(()=>{'use strict';
const files={wind:'wind-low',crt:'crt-startup',transition:'crt-transition',popup:'popup-snap',ecg:'ecg-beep',alien1:'alien-call-1',alien2:'alien-call-2',alien3:'alien-call-3',start:'start-screech',male1:'marine-male-1',male2:'marine-male-2',female1:'marine-female-1',female2:'marine-female-2',scientistMale:'scientist-male',scientistFemale:'scientist-female'};
let ctx=null,enabled=true,epoch=0,wind=null,windGain=null,windTarget=.16,unlocked=false,lastAlien=0;
const history=[];
const bytes=new Map(),buffers=new Map(),active=new Set(),pending=new Map(),failures=new Set();
function status(){let node=document.getElementById('audio-status');if(!node){node=document.createElement('button');node.id='audio-status';node.className='audio-status';node.type='button';node.setAttribute('aria-live','polite');node.addEventListener('click',()=>{unlock();retry()});document.body.append(node)}node.hidden=!enabled||(!failures.size&&(!ctx||ctx.state==='running'));node.textContent=failures.size?'Audio unavailable — tap to retry': 'Audio paused — tap to resume';}
function failed(key,error){failures.add(key);console.warn('Audio unavailable:',key,error);status()}
function context(){if(!ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C){failed('device',new Error('Web Audio unsupported'));return null}ctx=new C();ctx.addEventListener('statechange',()=>{status();if(ctx.state==='running'&&enabled&&unlocked)startWind()})}return ctx}
function fetchFile(key){if(!bytes.has(key))bytes.set(key,fetch(`./audio/${files[key]}.mp3`).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.arrayBuffer()}).catch(e=>{bytes.delete(key);failed(key,e);throw e}));return bytes.get(key)}
function buffer(key){if(buffers.has(key))return Promise.resolve(buffers.get(key));if(pending.has(key))return pending.get(key);const c=context();if(!c)return Promise.reject(new Error('Audio unavailable'));const task=fetchFile(key).then(data=>c.decodeAudioData(data.slice(0))).then(b=>{buffers.set(key,b);failures.delete(key);status();return b}).catch(e=>{failed(key,e);throw e}).finally(()=>pending.delete(key));pending.set(key,task);return task}
function source(b,volume,loop=false,key=''){history.push(key);if(history.length>80)history.shift();const src=ctx.createBufferSource(),gain=ctx.createGain();src.buffer=b;src.loop=loop;gain.gain.value=volume;src.connect(gain).connect(ctx.destination);active.add(src);src.onended=()=>{active.delete(src);src.disconnect();gain.disconnect()};return {src,gain}}
function play(key,volume=.5){if(!enabled||!unlocked)return;const token=epoch;buffer(key).then(b=>{if(!enabled||token!==epoch)return;const a=source(b,volume,false,key);a.src.start()}).catch(()=>{})}
function startWind(){if(!enabled||!unlocked||wind)return;const token=epoch;buffer('wind').then(b=>{if(!enabled||token!==epoch||wind)return;const a=source(b,0,true,'wind');wind=a.src;windGain=a.gain;a.src.start();ramp(windTarget,3.8)}).catch(()=>{})}
function ramp(target,seconds){windTarget=target;if(!windGain)return;let t=ctx.currentTime;if(windGain.gain.cancelAndHoldAtTime)windGain.gain.cancelAndHoldAtTime(t);else{windGain.gain.cancelScheduledValues(t);windGain.gain.setValueAtTime(windGain.gain.value,t)}windGain.gain.linearRampToValueAtTime(target,t+seconds)}
function unlock(){if(!enabled)return;const c=context();if(!c)return;unlocked=true;if(c.state!=='running')c.resume().then(()=>{failures.delete('device');startWind();status()}).catch(e=>failed('device',e));else startWind();for(const k of Object.keys(files))buffer(k).catch(()=>{});status()}
function preload(){for(const k of Object.keys(files))fetchFile(k).catch(()=>{})}
function retry(){for(const key of [...failures]){bytes.delete(key);pending.delete(key);if(files[key])buffer(key).catch(()=>{})}startWind()}
function setEnabled(value){enabled=value;epoch++;if(!enabled){for(const src of [...active]){try{src.stop()}catch{}}wind=null;windGain=null}else if(unlocked)unlock();status()}
function alien(loud=false){if(loud)return play('start',.85);let choice;do{choice=1+Math.floor(Math.random()*3)}while(choice===lastAlien);lastAlien=choice;play(`alien${choice}`,.24)}
window.ShipAudio={preload,unlock,setEnabled,play,alien,wind:(target,seconds=3)=>{windTarget=target;startWind();ramp(target,seconds)},stop:()=>setEnabled(false),diagnostics:()=>({enabled,state:ctx?.state||'locked',loaded:[...buffers.keys()],failures:[...failures],active:active.size,recent:history.slice()})};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&enabled&&unlocked)unlock()});
})();
