const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
function harness({failAudio=false}={}){
 let now=0,id=0;const timers=new Map(),calls=[],renders=[],digits=Array.from({length:5},()=>({textContent:''}));
 const listeners={},app={classList:{remove(){}},dataset:{},addEventListener:(key,fn)=>{(listeners['app:'+key]??=[]).push(fn)}};const screen={setAttribute(k,v){this[k]=v},querySelectorAll:()=>digits};const noop=()=>{};
 const audio=new Proxy({play:key=>{calls.push(key);if(failAudio)throw Error('Media failed')},capture:key=>calls.push(key),stopEffect:key=>calls.push('stop:'+key)},{get:(o,k)=>o[k]||noop});
 const context={window:{ShipArtwork:{CAPTURE_ARTS:['a'],SCIENTIST_ARTS:['s'],ITEM_ARTS:{},SENTRY_ART:{parts:"sentry-parts.png",emplacement:"gun-emplacement.png"},EMBEDDED_TILE_ART:{}}},ShipAudio:audio,WristTerminal:{cancel:()=>{},acknowledge:()=>{},afterOpen:fn=>fn(),isClosing:()=>false},ShipDropship:{stop:noop},document:{hidden:false,querySelector:s=>s==='.round-countdown'?screen:{textContent:''},querySelectorAll:()=>[],getElementById:()=>app,addEventListener:(key,fn)=>{(listeners[key]??=[]).push(fn)},body:{dataset:{},classList:{toggle:noop}}},localStorage:{removeItem:noop,getItem:()=>null,setItem:noop},location:{search:''},URLSearchParams,Date:class extends Date{static now(){return now}},performance:{now:()=>now},matchMedia:()=>({matches:false}),requestAnimationFrame:noop,setTimeout:(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id},clearTimeout:n=>timers.delete(n),setInterval:(fn,ms)=>{timers.set(++id,{fn,at:now+ms,repeat:ms});return id},clearInterval:n=>timers.delete(n),console:{...console,warn:noop},renders,failNextRender:false};
 let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');source=source.replace(/ render\(\);window.ShipReady=true;\s*\n\}\)\(\);\s*$/,`render=()=>{if(failNextRender){failNextRender=false;throw Error('Render failed')}renders.push(s?.phase)};finish=()=>render();cinemaStage=()=>{};alienStep=async()=>{s.alienMovesLeft=0};mountTerminal=()=>{};window.test={launch,canLaunch,grantClearance,selectPurge,finishLaunch,departurePlan,quarantineMarkup,orbitalMarkup,endingMarkup,swarmMarkup,syncQuarantineAudio,alienIcon,alienRevealed,marineToken,sentryAllowed,sentryAim,sentryIcon,fireSentry,spacedTerrain,validItemTarget,beginEscort,deliver,queueEquipment,countdownSweeps,bind,beginItem,useItem,targetPanel,HOME,DROPSHIP,newGame,runEvent,runMessages,showPopup,closePopup,roundCountdown,countdownValue,countdownMarkup,runAlienTurn,move,act,get s(){return s},get ui(){return ui}};})();`);
 vm.runInNewContext(source,context);const t=context.window.test;
 function fresh(){t.newGame(['A','B','C','D']);t.ui.boot='game';t.ui.cinematic=false;t.s.phase='play';t.s.players[0].role='crew';t.s.players[0].briefed=true;calls.length=0;renders.length=0;timers.clear()}
 function advance(ms){const end=now+ms;for(;;){const next=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;const [n,timer]=next;now=timer.at;if(timer.repeat)timer.at+=timer.repeat;else timers.delete(n);timer.fn()}now=end}
 fresh();return {t,context,calls,renders,digits,screen,advance,fresh,listeners};
}



const h=harness(),t=h.t;h.context.window.ShipArtwork.MARINE_ART='./marine-tokens.png';h.context.window.ShipArtwork.ALIEN_ART='./alien-overhead.png';
t.s.players.forEach(p=>p.pos='-3,0');t.s.alien='0,0';t.s.tiles['0,0'].known=true;
assert.equal(t.alienRevealed('0,0'),false);assert.ok(t.alienIcon().includes('alien-presence'));assert.ok(!t.alienIcon().includes('alien-sprite'));
t.s.players[3].pos='-2,0';assert.equal(t.alienRevealed('0,0'),true);assert.ok(t.alienIcon().includes('alien-sprite'));assert.ok(!t.alienIcon().includes('alien-presence'));
t.s.tiles['0,0'].known=false;assert.ok(t.alienIcon().includes('alien-sprite'));t.s.players[3].pos='-1,0';assert.ok(t.alienRevealed('0,0'));t.s.players[3].pos='0,0';assert.ok(t.alienRevealed('0,0'));
t.s.players.forEach(p=>p.pos='-3,0');assert.equal(t.alienIcon(),'');t.s.tiles['0,0'].known=true;
t.s.players[0].pos='-2,0';t.ui.alienMotion={from:'1,0',to:'0,0',started:0,duration:1000};const moving=t.alienIcon();assert.ok(moving.includes('alien-sprite')&&moving.includes('alien-presence'));assert.ok(moving.includes('begin="0.5s"'));assert.ok(moving.includes('type="translate"'));
for(let i=0;i<4;i++){t.s.turn=i;const p=t.s.players[i];p.scientist=true;p.captive=false;const token=t.marineToken(p,i,0,0);assert.ok(token.includes('marine-tokens.png'));assert.ok(token.includes(`viewBox="${i*543} 0 543 724"`));assert.ok(token.includes('active-turn'));assert.ok(token.includes('scientist-tag'));p.captive=true;assert.ok(t.marineToken(p,i,0,0).includes('captive'))}
console.log('PASS: alien range 0/1/2/3, nearest player, fog, motion transition and marine roles/turn/status.');