const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');let timers=[],calls=[];const noop=()=>{};const document={querySelector:()=>({textContent:''}),querySelectorAll:()=>[],addEventListener:noop,hidden:false,body:{dataset:{},classList:{toggle:noop}},getElementById:()=>({})};const ctx={window:{ShipArtwork:{CAPTURE_ARTS:['a'],SCIENTIST_ARTS:['s'],ITEM_ARTS:{},SENTRY_ART:{'sentry-base':'base','sentry-turret':'turret'},EMBEDDED_TILE_ART:{}}},document,localStorage:{removeItem:noop,getItem:()=>null,setItem:noop},ShipAudio:new Proxy({play:k=>calls.push(k)},{get:(o,k)=>o[k]||noop}),WristTerminal:{},location:{search:''},URLSearchParams,performance:{now:()=>0},setTimeout:(fn,ms)=>{if(ms===650){fn();return 0}timers.push({fn,ms});return timers.length},clearTimeout:noop,setInterval:noop,clearInterval:noop,requestAnimationFrame:noop,matchMedia:()=>({matches:false}),console};let src=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');src=src.replace(/ render\(\);window.ShipReady=true;\s*\n\}\)\(\);\s*$/,`render=()=>{};finish=()=>{};cinemaStage=()=>{};window.test={newGame,drop,deliver,arrive,fireSentry,sentryIcon,trackerContact,useItem,validItemTarget,board,get s(){return s},get ui(){return ui}};})();`);vm.runInNewContext(src,ctx);const t=ctx.window.test;
(async()=>{t.newGame(['A','B','C','D']);let s=t.s,p=s.players[0];assert.deepEqual(Array.from(s.players,x=>x.cargo[0]),['jetpack','sentry','medkit','flare']);assert.deepEqual(Array.from(s.players,x=>x.crewRole),['Sgt','Weapons Tech','Medic','Science Officer']);assert.equal(Object.values(s.tiles).filter(x=>x.site?.value==='sentry').length,1);assert.equal(Object.values(s.tiles).filter(x=>x.site?.value==='egg').length,0);
s.phase='play';t.ui.cinematic=false;s.ap=0;t.drop(0);assert.equal(s.ap,0);assert.equal(p.cargo.length,0);assert.equal(s.tiles[p.pos].loose.at(-1),'jetpack');p.cargo=['sentry'];t.ui.itemIndex=0;t.ui.targetHex=p.pos;t.useItem();assert.equal(s.sentries.length,1);assert.equal(s.ap,0);assert.ok(t.sentryIcon(s.sentries[0]).includes('animateTransform'));
s.alien='1,0';p.pos='1,0';await t.fireSentry('1,0');assert.equal(s.alien,s.nest);assert.equal(p.captive,false);assert.equal(s.sentries[0].armed,false);assert.equal(await t.fireSentry('1,0'),false);
s.alien='0,0';p.pos='0,0';for(const popup of [null,{kind:'event'},{kind:'scientist'}]){t.ui.popup=popup;t.ui.private=true;t.ui.sequence=true;assert.ok(t.trackerContact())}t.ui.popup={kind:'capture'};assert.equal(t.trackerContact(),null);t.ui.popup=null;
p.cargo=[];s.alien='0,0';t.arrive(s.nest,'moved');assert.deepEqual(Array.from(p.cargo),['egg']);assert.equal(s.nestEggFound,true);t.arrive(s.nest,'moved');assert.equal(p.cargo.length,1);
t.newGame(['A','B','C','D']);s=t.s;p=s.players[0];s.phase='play';p.captive=true;t.arrive(s.nest,'captured');assert.equal(s.nestEggFound,false);p.captive=false;p.pos='3,-2';p.scientist=true;p.scientistId=1;s.ap=1;t.deliver();assert.equal(s.delivered,1);assert.equal(t.ui.messages.at(-1).title,'Scientist onboard');
let reds=Object.keys(s.tiles).filter(k=>s.tiles[k].terrain==='gravity'&&s.tiles[k].pair==='red');s.alien=s.nest;t.arrive(reds[0],'moved');assert.equal(p.pos,reds[1]);assert.equal(t.ui.note,'');assert.ok(t.board().includes('active-turn'));assert.equal(t.board().includes('active-player'),false);
console.log('PASS: crew loadouts, cache sentry, free drop/deployment, scanning turret, pre-capture sentry retreat, tracker popup rules, unique nest egg excluding capture, scientist boarding report and silent Gravity Well transport');})().catch(e=>{console.error(e);process.exitCode=1});
