const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const script=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].map(m=>m[2]).find(code=>code.includes('window.ShipAudio='));
function harness(webAudio=true){
 const nodes=[],decodes=[],listeners={},nativePlays=[];let context;
 const keys=['background','introLoop','wristDrone','wind','crt','muthurLogin','tracker','wristOn','muthurOff','discovery','start','titleDrone','femaleCapture','maleCapture','ripley','chances','roundCountdown','endCredits','sporeBurst'];
 const embedded=Object.fromEntries(keys.map((key,i)=>[key,Buffer.from([i+1]).toString('base64')]));
 class Context{
  constructor(){context=this;this.state='suspended';this.currentTime=0;this.destination={};this.sampleRate=22050}
  decodeAudioData(bytes){return new Promise(resolve=>decodes.push({key:keys[new Uint8Array(bytes)[0]-1],resolve}))}
  resume(){this.state='running';return Promise.resolve()}
  createBuffer(channels,length,sampleRate){const data=Array.from({length:channels},()=>new Float32Array(length));return {key:"background",numberOfChannels:channels,length,sampleRate,duration:length/sampleRate,getChannelData:i=>data[i]}}
  createDynamicsCompressor(){return {threshold:{},knee:{},ratio:{},attack:{},release:{},connect(){},disconnect(){}}}
  createBiquadFilter(){return {frequency:{value:0},Q:{value:0},connect(node){this.output=node},disconnect(){}}}
  createGain(){return {gain:{value:0,setValueAtTime(value){this.value=value},linearRampToValueAtTime(value,time){this.ramp={value,time}}},connect(){},disconnect(){}}}
  createBufferSource(){const n={starts:0,stops:0,connect(gain){this.gain=gain},disconnect(){},start(...args){this.startArgs=args;this.starts++},stop(){this.stops++}};nodes.push(n);return n}
 }
 const media=[];
 function element(tag){const e={tag,paused:true,ended:false,readyState:4,currentTime:0,events:{},setAttribute(){},addEventListener(k,f){this.events[k]=f},append(){},play(){this.paused=false;nativePlays.push(this);return Promise.resolve()},pause(){this.paused=true}};if(tag==='audio')media.push(e);return e}
 const status=element('button');
 const document={hidden:false,getElementById:id=>id==='ship-audio-data'?{textContent:JSON.stringify(embedded)}:status,createElement:element,body:{append(){}},addEventListener:(k,fn)=>listeners[k]=fn};
 let timerId=0;const timers=new Map();const sandbox={setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId},clearTimeout:id=>timers.delete(id),window:{AudioContext:webAudio?Context:undefined,addEventListener(){}},document,Uint8Array,atob:s=>Buffer.from(s,'base64').toString('binary'),console};
 vm.runInNewContext(script,sandbox);
 function resolveAll(){for(const d of decodes.splice(0))d.resolve(d.key==='background'?Object.assign(context.createBuffer(2,500,100),{key:'background'}):{key:d.key,duration:d.key==='wristOn'?.813:d.key==='wristDrone'?1.55569:5})}
 return {api:sandbox.window.ShipAudio,nodes,decodes,listeners,document,media,nativePlays,timers,resolveAll,get context(){return context}};
}
async function tick(){for(let i=0;i<8;i++)await Promise.resolve()}
(async()=>{
 const ending=harness();ending.api.preload('game');assert.ok(!ending.decodes.some(d=>d.key==='endCredits'),'ending decode must not burden game preload');ending.api.unlock();ending.api.preload('ending');ending.resolveAll();await tick();ending.api.play('endCredits');await tick();assert.equal(ending.nativePlays.length,0,'orbital audio uses unlocked Web Audio');assert.ok(ending.nodes.some(n=>n.buffer?.key==='endCredits'&&n.starts===1));
 const h=harness();h.api.preload();assert.equal(h.nativePlays.length,0);assert.equal(h.nodes.length,0,'preparation is silent');h.api.unlock();h.api.play('wristDrone');h.api.stopEffect('wristDrone');h.resolveAll();await tick();assert.equal(h.nodes.filter(n=>n.buffer?.key==='wristDrone').length,0,'cancelled decode cannot start');
 h.api.play('wristDrone');await tick();const drone=h.nodes.find(n=>n.buffer.key==='wristDrone');assert.equal(drone.loop,true);assert.equal(drone.loopEnd,drone.buffer.duration);assert.equal(drone.gain.gain.value,.55);h.api.play('wristDrone');await tick();assert.equal(h.nodes.filter(n=>n.buffer.key==='wristDrone').length,1);
 h.context.state='suspended';h.api.play('wristDrone');await tick();assert.equal(h.context.state,'running');
 h.api.preload('game');h.resolveAll();await tick();const before=h.nodes.length;h.api.unlock();await tick();assert.equal(h.nodes.length,before,'unlock must not start prepared effects');assert.equal(h.nativePlays.length,0);
 h.api.play('start',.85);h.api.play('ripley');h.api.play('titleDrone');await tick();const requested=h.nodes.slice(before).map(n=>n.buffer.key);assert.deepEqual(requested.sort(),['ripley','start','titleDrone'],'mission launch requests Ripley, screech and score');
 let ended=0;h.api.onEnded('wristOn',()=>ended++);h.api.play('wristOn');await tick();const startup=h.nodes.find(n=>n.buffer.key==='wristOn');assert.equal(startup.gain.gain.value,.6);startup.onended();assert.equal(ended,1);
 h.api.play('roundCountdown');await tick();const countdown=h.nodes.find(n=>n.buffer.key==='roundCountdown');assert.equal(countdown.gain.gain.ramp,undefined,'countdown has no end fade');assert.equal(countdown.gain.gain.value,1);assert.equal(countdown.startArgs[0],0);
 h.api.play('discovery');await tick();assert.equal(h.nodes.find(n=>n.buffer.key==='discovery').gain.gain.value,1.5);
 h.api.play('ripley');await tick();assert.equal(h.nodes.find(n=>n.buffer.key==='ripley').gain.gain.value,.5);h.api.play('chances');await tick();assert.equal(h.nodes.find(n=>n.buffer.key==='chances').gain.gain.value,.5);h.api.wind(.1);assert.equal(h.nodes.find(n=>n.buffer.key==='wind'&&n.stops===0).gain.gain.value,.125);
 h.api.stopEffect('wristDrone');assert.equal(drone.stops,1);h.api.setEnabled(false);assert.ok(h.nodes.filter(n=>n.buffer.key==='titleDrone').every(n=>n.stops===1));h.api.setEnabled(true);await tick();assert.equal(h.nodes.filter(n=>n.buffer.key==='wristDrone').length,1,'unmute cannot revive a cancelled drone');
 h.api.play('wristDrone');await tick();h.document.hidden=true;h.listeners.visibilitychange();h.api.stopEffect('wristDrone');h.document.hidden=false;h.listeners.visibilitychange();await tick();assert.equal(h.nodes.filter(n=>n.buffer.key==='wristDrone').length,2,'visibility cannot restart a cancelled session');
 const bg=harness();bg.api.unlock();bg.api.gameLoop(true);bg.api.gameLoop(false);bg.resolveAll();await tick();assert.equal(bg.nodes.filter(n=>n.buffer?.key==='background').length,0,'late decode cannot start stopped background');bg.api.gameLoop(true);await tick();let music=bg.nodes.find(n=>n.buffer?.key==='background');assert.equal(music.loop,true);assert.equal(music.gain.gain.value,.35);bg.api.gameLoop(true);await tick();assert.equal(bg.nodes.filter(n=>n.buffer?.key==='background').length,1);bg.api.setEnabled(false);assert.equal(music.stops,1);bg.api.setEnabled(true);await tick();assert.equal(bg.nodes.filter(n=>n.buffer?.key==='background').length,2);bg.document.hidden=true;bg.listeners.visibilitychange();bg.document.hidden=false;bg.listeners.visibilitychange();await tick();assert.equal(bg.nodes.filter(n=>n.buffer?.key==='background').length,3);bg.api.gameLoop(false);bg.api.unlock();await tick();assert.equal(bg.nodes.filter(n=>n.buffer?.key==='background').length,3,'Launch stop survives unlock');
 const cap=harness();cap.api.unlock();cap.api.gameLoop(true);cap.resolveAll();await tick();const original=cap.nodes.find(n=>n.buffer?.key==='background');cap.context.currentTime=1;cap.api.capture('femaleCapture');cap.resolveAll();await tick();assert.equal(original.stops,1);cap.api.gameLoop(true);await tick();assert.equal(cap.nodes.filter(n=>n.buffer?.key==='background').length,1,'redraw cannot resume capture music');const timer=[...cap.timers.values()].find(t=>t.ms===4500);assert.ok(timer,'music returns half a second before five-second capture ends');timer.fn();await tick();const returned=cap.nodes.filter(n=>n.buffer?.key==='background').at(-1);assert.equal(returned.startArgs[1],1,'background resumes at saved position');assert.equal(returned.gain.gain.ramp.value,.35);assert.equal(returned.gain.gain.ramp.time,2.5);cap.api.gameLoop(false);
 const storm=harness();storm.api.unlock();await tick();storm.api.thunder();const thunder=storm.nodes.at(-1);assert.equal(thunder.starts,1);assert.equal(thunder.gain.output.gain.value,.975);const data=thunder.buffer.getChannelData(0);assert.ok(data.some(n=>Math.abs(n)>.01));assert.ok(data.slice(-100).every(n=>Math.abs(n)<.03),'thunder decays');storm.api.setEnabled(false);assert.equal(thunder.stops,1);storm.api.thunder();assert.equal(storm.nodes.at(-1),thunder,'mute suppresses thunder');
 const f=harness(false);f.api.preload('game');assert.equal(f.nativePlays.length,0);f.api.unlock();await tick();assert.equal(f.nativePlays.length,1,'legacy fallback unlock starts only wind');f.api.play('wristDrone');const wav=f.media.find(e=>e.src?.startsWith('data:audio/wav')&&!e.paused);assert.equal(wav.loop,true);assert.equal(wav.paused,false);f.api.stopEffect('wristDrone');assert.equal(wav.paused,true);
 console.log('PASS: silent preload/unlock, launch plays only requested cues, gain levels, natural startup completion, drone resumption, cancellation, mute and legacy fallback.');
})().catch(e=>{console.error(e);process.exitCode=1});
