const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
function harness({failAudio=false}={}){
 let now=0,id=0;const timers=new Map(),calls=[],renders=[],digits=Array.from({length:5},()=>({textContent:''}));
 const listeners={},app={classList:{remove(){}},dataset:{},addEventListener:(key,fn)=>{(listeners['app:'+key]??=[]).push(fn)}};const screen={setAttribute(k,v){this[k]=v},querySelectorAll:()=>digits};const noop=()=>{};
 const audio=new Proxy({play:key=>{calls.push(key);if(failAudio)throw Error('Media failed')},capture:key=>calls.push(key),stopEffect:key=>calls.push('stop:'+key)},{get:(o,k)=>o[k]||noop});
 const context={window:{ShipArtwork:{CAPTURE_ARTS:['a'],SCIENTIST_ARTS:['s'],ITEM_ARTS:{},SENTRY_ART:{parts:"sentry-parts.png",emplacement:"gun-emplacement.png"},EMBEDDED_TILE_ART:{}}},ShipAudio:audio,WristTerminal:{afterOpen:fn=>fn(),isClosing:()=>false},ShipDropship:{stop:noop},document:{hidden:false,querySelector:s=>s==='.round-countdown'?screen:{textContent:''},querySelectorAll:()=>[],getElementById:()=>app,addEventListener:(key,fn)=>{(listeners[key]??=[]).push(fn)},body:{dataset:{},classList:{toggle:noop}}},localStorage:{removeItem:noop,getItem:()=>null,setItem:noop},location:{search:''},URLSearchParams,Date:class extends Date{static now(){return now}},performance:{now:()=>now},matchMedia:()=>({matches:false}),requestAnimationFrame:noop,setTimeout:(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id},clearTimeout:n=>timers.delete(n),setInterval:(fn,ms)=>{timers.set(++id,{fn,at:now+ms,repeat:ms});return id},clearInterval:n=>timers.delete(n),console:{...console,warn:noop},renders,failNextRender:false};
 let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');source=source.replace(/ render\(\);window.ShipReady=true;\s*\n\}\)\(\);\s*$/,`render=()=>{if(failNextRender){failNextRender=false;throw Error('Render failed')}renders.push(s?.phase)};finish=()=>render();cinemaStage=()=>{};alienStep=async()=>{s.alienMovesLeft=0};mountTerminal=()=>{};window.test={sentryAllowed,sentryAim,sentryIcon,fireSentry,spacedTerrain,validItemTarget,beginEscort,deliver,queueEquipment,countdownSweeps,bind,beginItem,useItem,targetPanel,HOME,DROPSHIP,newGame,runEvent,runMessages,showPopup,closePopup,roundCountdown,countdownValue,countdownMarkup,runAlienTurn,move,act,get s(){return s},get ui(){return ui}};})();`);
 vm.runInNewContext(source,context);const t=context.window.test;
 function fresh(){t.newGame(['A','B','C','D']);t.ui.boot='game';t.ui.cinematic=false;t.s.phase='play';t.s.players[0].role='crew';t.s.players[0].briefed=true;calls.length=0;renders.length=0;timers.clear()}
 function advance(ms){const end=now+ms;for(;;){const next=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;const [n,timer]=next;now=timer.at;if(timer.repeat)timer.at+=timer.repeat;else timers.delete(n);timer.fn()}now=end}
 fresh();return {t,context,calls,renders,digits,screen,advance,fresh,listeners};
}


const h=harness(),t=h.t;
const expected={open:12,cover:3,event:8,gravity:4,bridge:4,spores:3,lander:1,dropship:1,nest:1};
for(let trial=0;trial<1000;trial++){h.fresh();const totals={};for(const [k,v] of Object.entries(t.s.tiles)){totals[v.terrain]=(totals[v.terrain]||0)+1;if(['event','gravity','bridge','spores'].includes(v.terrain)){const [q,r]=k.split(',').map(Number);for(const [dq,dr] of [[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]])assert.notEqual(t.s.tiles[`${q+dq},${r+dr}`]?.terrain,v.terrain,`${v.terrain} adjacent in map ${trial}`)}}assert.deepEqual(totals,expected)}
for(const terrain of ['gravity','void','nest','lander','dropship']){h.fresh();t.s.players[0].pos='1,0';t.s.tiles['1,0'].terrain=terrain;t.s.players[0].cargo=['sentry'];const ap=t.s.ap;t.beginItem(0);assert.equal(t.ui.mode,'');assert.equal(t.ui.messages[0].title,'UNABLE TO DEPLOY HERE');assert.equal(t.s.players[0].cargo.length,1);assert.equal(t.s.ap,ap);assert.equal(t.s.sentries.length,0)}
for(const k of [t.HOME,t.DROPSHIP]){h.fresh();t.s.players[0].pos=k;t.s.tiles[k].terrain='open';assert.equal(t.sentryAllowed(k),false)}
h.fresh();t.s.players[0].pos=t.s.nest;assert.equal(t.sentryAllowed(t.s.nest),false);
for(const terrain of ['event','spores','bridge','cover','open']){h.fresh();const p=t.s.players[0],tile=t.s.tiles['1,0'];p.pos='1,0';p.cargo=['sentry'];tile.terrain=terrain;t.s.ap=0;const site=tile.site;t.beginItem(0);assert.equal(t.ui.targetHex,'1,0');t.useItem();assert.equal(tile.terrain,'open');assert.equal(tile.emplacement,true);assert.equal(tile.site,site);assert.equal(p.cargo.length,0);assert.equal(t.s.ap,0);assert.equal(t.s.sentries.length,1);assert.equal(t.sentryAllowed('1,0'),false)}
// Recheck eligibility at confirm: changed terrain never consumes the gun.
h.fresh();t.s.players[0].pos='1,0';t.s.players[0].cargo=['sentry'];t.s.tiles['1,0'].terrain='open';t.beginItem(0);t.s.tiles['1,0'].terrain='void';t.useItem();assert.equal(t.s.players[0].cargo.length,1);assert.equal(t.ui.messages[0].title,'UNABLE TO DEPLOY HERE');
// Every interpolated ray remains clear of a padded countdown/text rectangle.
function crosses(a,b,lo=[45.1,390.1],hi=[409.9,519.9]){let enter=0,exit=1;for(let n=0;n<2;n++){const d=b[n]-a[n];if(Math.abs(d)<1e-8){if(a[n]<lo[n]||a[n]>hi[n])return false}else{const x=(lo[n]-a[n])/d,y=(hi[n]-a[n])/d;enter=Math.max(enter,Math.min(x,y));exit=Math.min(exit,Math.max(x,y));if(enter>exit)return false}}return true}
for(const values of t.countdownSweeps())for(let i=0;i<values.length-1;i++){const a=values[i].match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/g).map(Number),b=values[i+1].match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/g).map(Number);for(let step=0;step<=10;step++){const p=a.map((v,n)=>v+(b[n]-v)*step/10);assert.equal(crosses(p.slice(0,2),p.slice(2,4)),false);assert.equal(crosses(p.slice(2,4),p.slice(4,6)),false);assert.equal(crosses(p.slice(0,2),p.slice(2,4),[55,330],[315,375]),false);assert.equal(crosses(p.slice(2,4),p.slice(4,6),[55,330],[315,375]),false)}}
(async()=>{h.fresh();const gun={hex:'1,0',armed:true,aim:0,firingUntil:0};t.s.sentries=[gun];t.s.alien='2,0';const first=t.sentryAim(gun);assert.ok(t.sentryIcon(gun).includes('sentry-active-light'));assert.ok(t.sentryIcon(gun).includes('calcMode="spline"'));t.s.alien='1,1';assert.notEqual(t.sentryAim(gun),first);const target=t.s.alien,aim=t.sentryAim(gun,target);const fired=t.fireSentry(target);assert.equal(gun.armed,false);assert.equal(gun.aim,aim);assert.ok(!t.sentryIcon(gun).includes('sentry-active-light'));assert.ok(!t.sentryIcon(gun).includes('animateTransform'));assert.ok(t.sentryIcon(gun).includes('sentry-flash'));assert.ok(t.sentryIcon(gun).includes('class="sentry-upper"'));assert.ok(!t.sentryIcon(gun).includes('rotate(-115.15)'));assert.ok(!t.sentryIcon(gun).includes('scale('));h.advance(2253);for(let i=0;i<8;i++)await Promise.resolve();assert.equal(await fired,true);assert.equal(t.s.alien,t.s.nest);assert.equal(gun.firingUntil,0);assert.ok(!t.sentryIcon(gun).includes('sentry-flash'));console.log('PASS: 1,000 generated boards retain counts and same-type spacing; illegal and atomic deployments, open-ground conversion, countdown clearance, tracking/LED/fire lifecycle.');})().catch(e=>{console.error(e);process.exitCode=1});
