const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
function harness({failAudio=false}={}){
 let now=0,id=0;const timers=new Map(),calls=[],renders=[],digits=Array.from({length:5},()=>({textContent:''}));
 const listeners={},app={classList:{remove(){}},dataset:{},addEventListener:(key,fn)=>{(listeners['app:'+key]??=[]).push(fn)}};const screen={setAttribute(k,v){this[k]=v},querySelectorAll:()=>digits};const noop=()=>{};
 const audio=new Proxy({play:key=>{calls.push(key);if(failAudio)throw Error('Media failed')},capture:key=>calls.push(key),stopEffect:key=>calls.push('stop:'+key)},{get:(o,k)=>o[k]||noop});
 const context={window:{ShipArtwork:{CAPTURE_ARTS:['a'],SCIENTIST_ARTS:['s'],ITEM_ARTS:{},SENTRY_ART:{parts:"sentry-parts.png",emplacement:"gun-emplacement.png"},EMBEDDED_TILE_ART:{}}},ShipAudio:audio,WristTerminal:{cancel:()=>{},acknowledge:()=>{},afterOpen:fn=>fn(),isClosing:()=>false},ShipDropship:{stop:noop},document:{hidden:false,querySelector:s=>s==='.round-countdown'?screen:{textContent:''},querySelectorAll:()=>[],getElementById:()=>app,addEventListener:(key,fn)=>{(listeners[key]??=[]).push(fn)},body:{dataset:{},classList:{toggle:noop}}},localStorage:{removeItem:noop,getItem:()=>null,setItem:noop},location:{search:''},URLSearchParams,Date:class extends Date{static now(){return now}},performance:{now:()=>now},matchMedia:()=>({matches:false}),requestAnimationFrame:noop,setTimeout:(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id},clearTimeout:n=>timers.delete(n),setInterval:(fn,ms)=>{timers.set(++id,{fn,at:now+ms,repeat:ms});return id},clearInterval:n=>timers.delete(n),console:{...console,warn:noop},renders,failNextRender:false};
 let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');source=source.replace(/ render\(\);window.ShipReady=true;\s*\n\}\)\(\);\s*$/,`render=()=>{if(failNextRender){failNextRender=false;throw Error('Render failed')}renders.push(s?.phase)};finish=()=>render();cinemaStage=()=>{};alienStep=async()=>{s.alienMovesLeft=0};mountTerminal=()=>{};window.test={launch,canLaunch,grantClearance,selectPurge,finishLaunch,departurePlan,quarantineMarkup,orbitalMarkup,endingMarkup,syncQuarantineAudio,heading,marineFacing,alienFacing,marineToken,alienIcon,arrive,sentryAllowed,sentryAim,sentryIcon,fireSentry,spacedTerrain,validItemTarget,beginEscort,deliver,queueEquipment,countdownSweeps,bind,beginItem,useItem,targetPanel,HOME,DROPSHIP,newGame,runEvent,runMessages,showPopup,closePopup,roundCountdown,countdownValue,countdownMarkup,runAlienTurn,move,act,get s(){return s},get ui(){return ui}};})();`);
 vm.runInNewContext(source,context);const t=context.window.test;
 function fresh(){t.newGame(['A','B','C','D']);t.ui.boot='game';t.ui.cinematic=false;t.s.phase='play';t.s.players[0].role='crew';t.s.players[0].briefed=true;calls.length=0;renders.length=0;timers.clear()}
 function advance(ms){const end=now+ms;for(;;){const next=[...timers].filter(([,v])=>v.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;const [n,timer]=next;now=timer.at;if(timer.repeat)timer.at+=timer.repeat;else timers.delete(n);timer.fn()}now=end}
 fresh();return {t,context,calls,renders,digits,screen,advance,fresh,listeners};
}




const h=harness(),t=h.t;h.context.window.ShipArtwork.PATCH_ART='role-patches.png';h.context.window.ShipArtwork.MARINE_ART='marine-tokens.png';h.context.window.ShipArtwork.ALIEN_ART='alien-overhead.png';
const p=t.s.players[0];p.pos=t.HOME;assert.ok(t.marineToken(p,0,0,0).includes('apc-seat-initial'));assert.ok(!t.marineToken(p,0,0,0).includes('marine-facing'));p.pos=t.DROPSHIP;assert.ok(t.marineToken(p,0,0,0).includes('marine-facing'));
p.pos=t.HOME;t.s.tiles['1,0'].terrain='open';t.s.tiles['1,0'].site=null;t.s.alien='-3,0';t.arrive('1,0','moved');assert.equal(p.facing,90);assert.ok(t.marineToken(p,0,0,0).includes('rotate(-90)'));assert.equal(t.marineFacing(p,0).guard,false);
t.s.turn=1;assert.equal(t.marineFacing(p,0).guard,true);assert.ok(t.marineToken(p,0,0,0).includes('calcMode="spline"'));t.s.alien='1,1';assert.equal(t.marineFacing(p,0).guard,false);assert.equal(t.marineFacing(p,0).angle,t.heading(p.pos,t.s.alien));p.captive=true;assert.equal(t.marineFacing(p,0).guard,false);p.captive=false;
t.ui.alienMotion={from:'0,0',to:'1,0'};assert.equal(t.alienFacing(),90);t.ui.alienMotion=null;t.s.alien='0,0';t.s.alienMind={mode:'stalk',target:0};assert.equal(t.alienFacing(),90);t.s.alienMind.mode='withdraw';t.s.alienFacing=-60;assert.equal(t.alienFacing(),-60);
assert.ok(t.alienIcon().includes('alien-facing'));const source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');assert.ok(source.includes("ShipBuild='v96'"));assert.ok(source.includes("textContent='v96'"));assert.ok(source.includes('ShipTerrain.mount'));
console.log('PASS: vehicle seat initials, movement facing, idle guard/detection, captured guard disabled, alien travel/target/last facing, APC scale and visible v96 label.');
