(()=>{'use strict';
const KEY='last-shuttle-playtest-v4',R=3,HOME='0,0',SHUTTLE='3,-2',NEST='-3,3';
const DIRS=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
const CELLS=[];for(let q=-R;q<=R;q++)for(let r=-R;r<=R;r++)if(Math.abs(q+r)<=R)CELLS.push({q,r,k:`${q},${r}`});
const MAP=Object.fromEntries(CELLS.map(c=>[c.k,c]));
const COLOURS=['#ffd36d','#67d7e7','#ff8b7c','#bd9af3','#8ce0a4','#fa9bc2'];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dist=(a,b)=>{let A=MAP[a],B=MAP[b];return Math.max(Math.abs(A.q-B.q),Math.abs(A.r-B.r),Math.abs(A.q+A.r-B.q-B.r))};
const ring=k=>{let c=MAP[k];return Math.max(Math.abs(c.q),Math.abs(c.r),Math.abs(c.q+c.r))};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const take=a=>a.splice(Math.floor(Math.random()*a.length),1)[0];
let s;try{s=JSON.parse(localStorage.getItem(KEY))}catch{}
let ui={selected:HOME,mode:'',note:'',private:false,privateKind:'',privateResult:'',scan:false,transfer:false,itemIndex:null,targetHex:null};
const tile=k=>s.tiles[k],me=()=>s.players[s.turn];
function save(){localStorage.setItem(KEY,JSON.stringify(s))}function log(t){s.log.unshift(`R${s.round}: ${t}`);s.log=s.log.slice(0,40)}
function notice(t){ui.note=t;render()}function finish(){save();render()}
function newGame(names){let keys=shuffle(CELLS.filter(c=>![HOME,SHUTTLE,NEST].includes(c.k)).map(c=>c.k));
 let terrain=shuffle([...Array(12).fill('open'),...Array(4).fill('bridge'),...Array(4).fill('tunnel'),...Array(3).fill('cover'),...Array(3).fill('spores'),...Array(8).fill('event')]);
 let tunnels=shuffle(['A','A','B','B']);let tiles={};for(let c of CELLS){let type=c.k===HOME?'lander':c.k===SHUTTLE?'shuttle':c.k===NEST?'nest':terrain.pop();tiles[c.k]={terrain:type,known:ring(c.k)<=1||[SHUTTLE,NEST].includes(c.k),pair:type==='tunnel'?tunnels.pop():null,site:null,loose:[],groundScientists:0,eventSpent:false}}
 let sites=shuffle(keys.filter(k=>![HOME,SHUTTLE,NEST].includes(k)));for(let v of shuffle(['scientist','scientist','false','false']))tiles[sites.pop()].site={kind:'distress',value:v,status:'hidden'};
 for(let v of shuffle(['egg','jetpack','flare','scanner','medkit','specimen']))tiles[sites.pop()].site={kind:'cargo',value:v,status:'hidden'};
 let roles=shuffle(['saboteur',...Array(names.length-1).fill('crew')]);
 s={phase:'handoff',round:1,turn:0,moves:2,ap:1,players:names.map((name,i)=>({name,role:roles[i],briefed:false,pos:HOME,scientist:false,cargo:[],captive:false,safeNest:false,quietRound:0})),tiles,alien:NEST,noise:[],lure:null,scans:2,delivered:0,eggDestroyed:false,decoys:2,pendingSabotage:[],events:shuffle(['Alien lunge','Bridge tremor','Spore burst','Scan battery','Supply pod','Quiet cover','Risky salvage','Distress coordinates']),pendingEvent:null,alert:'',log:['R1: Find two scientists and keep the egg off the shuttle.'],winner:null};
 ui={selected:HOME,mode:'',note:'',private:false,privateKind:'',privateResult:'',scan:false,transfer:false,itemIndex:null,targetHex:null};finish()}
function adjacent(k){return DIRS.map(([dq,dr])=>`${MAP[k].q+dq},${MAP[k].r+dr}`).filter(x=>tile(x)&&tile(x).terrain!=='void')}
function spend(){s.ap=0;finish()}
function noise(k){s.noise.push(k)}
function move(k,jet=false){if(s.phase!=='play'||s.pendingEvent)return;let p=me();if(p.captive)return notice('You are captive. Use your action to escape first.');if(!tile(k)||tile(k).terrain==='void')return notice('That route has collapsed.');
 let pair=tile(p.pos).terrain==='tunnel'&&tile(k).terrain==='tunnel'&&tile(k).known&&tile(p.pos).pair===tile(k).pair&&p.pos!==k;
 if(jet){if(s.ap<1||!p.cargo.includes('jetpack')||dist(p.pos,k)<1||dist(p.pos,k)>3)return notice('Jetpack range is one to three hexes.');p.cargo.splice(p.cargo.indexOf('jetpack'),1);s.ap=0;noise(k);log(`${p.name} used a jetpack.`)}
 else{if(s.moves<1)return notice('No moves remain this turn.');if(dist(p.pos,k)!==1&&!pair)return notice('Tap an adjacent hex, or a discovered matching tunnel.');s.moves--}
 p.pos=k;p.safeNest=false;tile(k).known=true;ui.selected=k;ui.mode='';ui.note='';log(`${p.name} moved${pair?' through a tunnel':''}.`);
 if(tile(k).terrain==='spores'){noise(k);log(`Spores at ${k} drew the creature's attention.`)}
 if(k===s.alien)capture();
 if(!p.captive&&tile(k).terrain==='event'&&!tile(k).eventSpent){s.moves=0;triggerEvent(k)}
 finish()}
function capture(){let caught=s.players.filter(p=>p.pos===s.alien&&!p.captive&&!(p.safeNest&&p.pos===NEST));for(let p of caught){let where=p.pos,parts=[];if(p.scientist){p.scientist=false;tile(where).groundScientists++;parts.push('dropped their scientist')}if(p.cargo.length){let j=Math.floor(Math.random()*p.cargo.length);tile(NEST).loose.push(p.cargo.splice(j,1)[0]);parts.push('lost random cargo at the nest')}p.pos=NEST;p.captive=true;p.safeNest=false;if(p===me()){s.moves=0;s.ap=0}let msg=`CREATURE CAPTURE: ${p.name} ${parts.length?parts.join(' and ')+', ':''}was taken to the nest.`;s.alert=msg;ui.note=msg;log(msg)}}
function alienStep(targetOverride){let target=targetOverride||s.lure||s.noise.at(-1);if(!target){let visible=s.players.filter(p=>!p.captive&&tile(p.pos).terrain!=='cover'&&p.quietRound!==s.round);if(!visible.length)visible=s.players.filter(p=>!p.captive);target=(visible.length?visible:s.players).reduce((best,p)=>dist(p.pos,s.alien)<dist(best.pos,s.alien)?p:best).pos}
 let opts=adjacent(s.alien).sort((a,b)=>dist(a,target)-dist(b,target));if(opts.length&&dist(opts[0],target)<dist(s.alien,target))s.alien=opts[0];capture()}
function startNext(i){s.turn=i;s.moves=2;s.ap=1;s.phase='handoff'}
function roundEnd(){s.alert='';for(let sabotage of s.pendingSabotage||[]){if(sabotage.type==='jam'&&s.scans>0){s.scans--;log('Scanner interference cost the team one charge.')}if(sabotage.type==='decoy'){let t=tile(sabotage.hex);if(t&&!t.site&&!['void','lander','shuttle','nest'].includes(t.terrain)){t.site={kind:'distress',value:'false',status:'hidden',decoy:true};t.known=true;log('A new distress signal appeared.')}}if(sabotage.type==='redirect'){s.lure=sabotage.hex;log('An unexplained signal redirected the creature.')}}s.pendingSabotage=[];for(let i=0;i<2;i++)alienStep();s.lure=null;s.noise=[];for(let p of s.players)p.safeNest=false;
 if(s.round>=9){s.winner='saboteur';s.phase='over';log('The shuttle window closed. The saboteur wins.')}else{s.round++;startNext(0)}}
function endTurn(){if(s.phase!=='play'||s.pendingEvent)return;ui.mode='';ui.note='';ui.privateResult='';if(s.turn===s.players.length-1)roundEnd();else startNext(s.turn+1);finish()}
function triggerEvent(k){let event=s.events.shift()||'Quiet cover';let t=tile(k);t.terrain='open';t.eventSpent=true;log(`${me().name} triggered an event: ${event}.`);ui.note=`EVENT: ${event}. Movement ends here.`;
 if(event==='Alien lunge'){alienStep(me().pos)}
 if(event==='Bridge tremor'){let choices=Object.keys(s.tiles).filter(x=>canCollapse(x));if(choices.length){let b=take(choices);tile(b).terrain='void';tile(b).known=true;log(`A bridge collapsed at ${b}.`)}}
 if(event==='Spore burst'){noise(k);alienStep(k)}
 if(event==='Scan battery'){s.scans++;log('The team found one scan charge.')}
 if(event==='Supply pod'){if(me().cargo.length<2){me().cargo.push('flare');ui.privateResult='You found a FLARE.'}else tile(k).loose.push('flare');log('A flare was recovered.')}
 if(event==='Quiet cover'){me().quietRound=s.round;log(`${me().name} is hidden from the creature this round unless they make noise.`)}
 if(event==='Risky salvage'||event==='Distress coordinates')s.pendingEvent=event}
function chooseEvent(takeRisk){let event=s.pendingEvent;if(!event)return;let p=me();if(takeRisk&&event==='Risky salvage'){if(p.cargo.length<2){p.cargo.push('jetpack');ui.privateResult='You recovered a JETPACK.'}else tile(p.pos).loose.push('jetpack');alienStep(p.pos);log(`${p.name} salvaged a jetpack, drawing the creature.`)}
 if(takeRisk&&event==='Distress coordinates'){let hidden=Object.entries(s.tiles).filter(([k,t])=>t.site?.kind==='distress'&&t.site.status==='hidden');if(hidden.length){let [k,t]=take(hidden);t.known=true;if(t.site.value==='false'){t.site.status='cleared';log(`A false distress signal was exposed at ${k}.`)}else{t.site.status='found';log(`A scientist was located at ${k}.`)}}else log('No distress signals remained.');if(s.scans>0){s.scans--;log('The transmission used one scan charge.')}}
 if(!takeRisk)log(`${p.name} passed on the event offer.`);s.pendingEvent=null;finish()}
function search(){let p=me(),t=tile(p.pos);if(s.ap<1||p.captive||!t.site||t.site.status!=='hidden')return;if(t.site.kind==='cargo'&&p.cargo.length>=2)return notice('Cargo limit: drop something first.');let v=t.site.value;t.site.status=v==='scientist'?'found':'cleared';if(t.site.kind==='cargo'){p.cargo.push(v);ui.privateResult=`You found ${v.toUpperCase()}. Keep this private.`;log(`${p.name} took face-down cargo.`)}else if(v==='scientist')log(`${p.name} found a scientist.`);else log(`${p.name} found a false distress signal.`);noise(p.pos);spend()}
function escort(){let p=me(),t=tile(p.pos);if(s.ap<1||p.captive||p.scientist)return;if(t.groundScientists)t.groundScientists--;else if(t.site?.value==='scientist'&&t.site.status==='found')t.site.status='rescued';else return;p.scientist=true;log(`${p.name} is escorting a scientist.`);spend()}
function deliver(){let p=me();if(s.ap<1||p.pos!==SHUTTLE||!p.scientist||p.captive)return;p.scientist=false;s.delivered++;log(`${p.name} delivered scientist ${s.delivered}/2.`);spend()}
function escapeNest(){let p=me();if(s.ap<1||!p.captive)return;p.captive=false;p.safeNest=true;log(`${p.name} escaped the alien nest.`);spend()}
function freeCaptive(i){let p=me(),other=s.players[i];if(s.ap<1||p.captive||!other?.captive||dist(p.pos,NEST)>1)return;other.captive=false;other.safeNest=true;log(`${p.name} freed ${other.name} from the nest.`);spend()}
function drop(i){let p=me();if(s.ap<1||p.captive||!p.cargo[i])return;tile(p.pos).loose.push(p.cargo.splice(i,1)[0]);log(`${p.name} dropped face-down cargo.`);spend()}
function collect(i){let p=me(),a=tile(p.pos).loose;if(s.ap<1||p.captive||p.cargo.length>=2||!a[i])return;p.cargo.push(a.splice(i,1)[0]);ui.privateResult=`You picked up ${p.cargo.at(-1).toUpperCase()}.`;log(`${p.name} picked up face-down cargo.`);spend()}
function validItemTarget(v,k){return !!tile(k)&&tile(k).terrain!=='void'&&(v==='flare'?dist(me().pos,k)<=3:v==='jetpack'?dist(me().pos,k)>=1&&dist(me().pos,k)<=3:v==='scanner'?k===me().pos:v==='medkit'?k===HOME:false)}
function beginItem(i){let v=me().cargo[i];if(s.ap<1||me().captive||!['flare','jetpack','scanner','medkit'].includes(v))return;ui.private=false;ui.privateKind='';ui.itemIndex=i;ui.targetHex=null;ui.mode='itemTarget';ui.note=`Choose a target hex for ${v.toUpperCase()}. Highlighted hexes are valid. Confirm or cancel before the item is used.`;render()}
function cancelTarget(){ui.mode='';ui.itemIndex=null;ui.targetHex=null;ui.note='';render()}
function useItem(){let p=me(),i=ui.itemIndex,v=p.cargo[i],k=ui.targetHex;if(s.ap<1||p.captive||!validItemTarget(v,k))return notice('Select a highlighted target hex.');p.cargo.splice(i,1);s.ap=0;ui.mode='';ui.itemIndex=null;ui.targetHex=null;ui.note='';
 if(v==='flare'){s.lure=k;log(`${p.name} fired a flare towards ${k}. The creature will follow it at round end.`)}
 if(v==='jetpack'){p.pos=k;tile(k).known=true;noise(k);log(`${p.name} landed a jetpack at ${k}.`);if(k===s.alien)capture();if(!p.captive&&tile(k).terrain==='event'&&!tile(k).eventSpent){s.moves=0;triggerEvent(k)}}
 if(v==='scanner'){s.scans++;log(`${p.name} recharged the scanner.`)}
 if(v==='medkit'){p.pos=HOME;log(`${p.name} returned to the lander with a medkit.`);if(p.pos===s.alien)capture()}
 finish()}
function incinerate(i){let p=me();if(s.ap<1||p.captive||p.pos!==HOME||!p.cargo[i])return;let v=p.cargo.splice(i,1)[0];if(v==='egg')s.eggDestroyed=true;log(`${p.name} incinerated ${v==='egg'?'THE EGG':`a ${v}`}.`);noise(HOME);spend()}
function scan(pi,i){let p=me(),other=s.players[pi];if(s.ap<1||p.captive||s.scans<1||!other||p.pos!==other.pos||!other.cargo[i])return notice('Stand with a cargo carrier to scan.');let v=other.cargo[i];s.scans--;log(`${p.name} scanned ${other.name}'s cargo: ${v.toUpperCase()}.`);if(v==='egg'){other.cargo.splice(i,1);s.eggDestroyed=true;log('The egg was confiscated and destroyed.')}ui.note=`Scan: ${v.toUpperCase()}${v==='egg'?' — destroyed':''}`;ui.scan=false;spend()}
function transfer(pi,i,steal){let p=me(),other=s.players[pi];if(s.ap<1||p.captive||!other||pi===s.turn||dist(p.pos,other.pos)>(steal?1:0))return;if(steal){if(!other.cargo.length||p.cargo.length>=2)return;let j=Math.floor(Math.random()*other.cargo.length);p.cargo.push(other.cargo.splice(j,1)[0]);ui.privateResult=`You snatched ${p.cargo.at(-1).toUpperCase()}.`;log(`${p.name} snatched random cargo from ${other.name}.`)}else{if(!p.cargo[i]||other.cargo.length>=2)return;other.cargo.push(p.cargo.splice(i,1)[0]);log(`${p.name} passed cargo to ${other.name}.`)}ui.transfer=false;spend()}
function canCollapse(k){let t=tile(k);return t?.terrain==='bridge'&&!t.site&&!t.groundScientists&&!t.loose.length&&!s.players.some(p=>p.pos===k)&&s.alien!==k}
function collapse(k){let p=me();if(s.ap<1||p.captive||dist(p.pos,k)>1||!canCollapse(k))return notice('Choose an adjacent empty bridge.');tile(k).terrain='void';tile(k).known=true;log(`${p.name} collapsed a bridge at ${k}.`);spend()}
function jamScan(){if(me().role!=='saboteur'||s.ap<1||me().captive||s.scans<1)return;s.pendingSabotage.push({type:'jam'});ui.private=false;ui.privateKind='';s.ap=0;ui.note='Your interference is queued for the end of this round.';finish()}
function plant(k){let p=me(),t=tile(k);if(p.role!=='saboteur'||s.ap<1||p.captive||s.decoys<1||dist(p.pos,k)>1||!t||t.site||['void','lander','shuttle','nest'].includes(t.terrain))return notice('Choose an adjacent empty hex.');s.pendingSabotage.push({type:'decoy',hex:k});s.decoys--;ui.mode='';ui.note='False signal queued for round end.';s.ap=0;finish()}
function redirect(k){let p=me();if(p.role!=='saboteur'||s.ap<1||p.captive||!tile(k)||dist(p.pos,k)>2)return notice('Choose a hex within two spaces.');s.pendingSabotage.push({type:'redirect',hex:k});ui.mode='';ui.note='Creature redirection queued for round end.';s.ap=0;finish()}
function launch(){if(s.phase!=='play'||s.delivered!==2||me().pos!==SHUTTLE||s.ap<1||me().captive)return;s.phase='launch';finish()}
function finishLaunch(){let people=[...document.querySelectorAll('.boarding:checked')].map(e=>+e.value);if(!people.length)return notice('Choose at least one passenger.');s.winner=people.some(i=>s.players[i].cargo.includes('egg'))?'saboteur':'crew';s.phase='over';log(s.winner==='crew'?'The scientists escaped without the egg. Crew win.':'THE EGG BOARDED. Saboteur wins.');finish()}
const label=t=>({lander:'Lander',shuttle:'Shuttle',nest:'Alien nest',open:'Open ground',bridge:'Bridge',tunnel:'Tunnel',cover:'Cover',spores:'Spore field',event:'Event tile',void:'Collapsed hex'})[t]||t;
function hexInfo(k){let t=tile(k);return `<div class="notice"><strong>${t.known?label(t.terrain):'Unexplored hex'}</strong> · ${k}${t.pair&&t.known?` · tunnel ${t.pair}`:''}${t.site?.status==='hidden'?` · ${t.site.kind==='cargo'?'cargo site':'distress signal'}`:''}${t.site?.status==='found'||t.groundScientists?' · scientist waiting':''}${t.loose.length?` · ${t.loose.length} dropped cargo`:''}${k===s.alien?' · CREATURE HERE':''}</div>`}
function targetValid(k){if(ui.mode==='itemTarget')return validItemTarget(me().cargo[ui.itemIndex],k);if(ui.mode==='decoy'){let t=tile(k);return !!t&&dist(me().pos,k)<=1&&!t.site&&!['void','lander','shuttle','nest'].includes(t.terrain)}if(ui.mode==='redirect')return !!tile(k)&&dist(me().pos,k)<=2;return false}
function board(){const S=52,X=360,Y=315;let out=['<svg viewBox="0 0 720 630" role="img" aria-label="Hexagonal alien planet board">'];for(let c of CELLS){let t=tile(c.k),x=X+Math.sqrt(3)*S*(c.q+c.r/2),y=Y+1.5*S*c.r;let col=!t.known?'#19392e':({lander:'#246b6b',shuttle:'#a28438',nest:'#653f59',open:'#31574c',bridge:'#746657',tunnel:'#315b73',cover:'#315f4a',spores:'#5a6840',event:'#6c5680',void:'#0b111c'})[t.terrain];let pts=Array.from({length:6},(_,i)=>`${x+S*Math.cos((60*i-30)*Math.PI/180)},${y+S*Math.sin((60*i-30)*Math.PI/180)}`).join(' ');let mark=!t.known?'?':({lander:'LANDER',shuttle:'SHUTTLE',nest:'NEST',bridge:'BRIDGE',tunnel:`TUN ${t.pair}`,cover:'COVER',spores:'SPORES',event:'EVENT',void:'×'})[t.terrain]||'';let valid=!!ui.mode&&targetValid(c.k);
 out.push(`<g data-hex="${c.k}"><polygon class="hex ${ui.selected===c.k?'sel':''} ${s.alien===c.k?'danger':''} ${valid?'target':''} ${ui.targetHex===c.k?'chosen':''} ${!ui.mode&&dist(me().pos,c.k)===1&&s.moves>0?'reach':''}" points="${pts}" fill="${col}" fill-opacity=".84"/><text class="celltext" x="${x}" y="${y+5}">${mark}</text>`);
 if(t.site?.status==='hidden')out.push(`<circle cx="${x-28}" cy="${y-26}" r="13" fill="${t.site.kind==='cargo'?'#e4b557':'#64d7d4'}"/><text class="marker" x="${x-28}" y="${y-19}" fill="#102236">${t.site.kind==='cargo'?'◆':'!'}</text>`);
 if(t.site?.status==='found'||t.groundScientists)out.push(`<text class="marker" x="${x-28}" y="${y-22}" fill="#a2ffd7">✚</text>`);
 if(t.loose.length)out.push(`<circle cx="${x+26}" cy="${y-24}" r="11" fill="#ffdc84"/><text class="marker" x="${x+26}" y="${y-18}" fill="#112134" style="font-size:13px">${t.loose.length}</text>`);
 s.players.forEach((p,i)=>{if(p.pos!==c.k)return;let n=s.players.slice(0,i).filter(a=>a.pos===c.k).length,tx=x-21+(n%3)*21,ty=y+25+Math.floor(n/3)*20;out.push(`<circle class="token" cx="${tx}" cy="${ty}" r="12" fill="${COLOURS[i]}"/><text class="tokenletter" x="${tx}" y="${ty+5}">${i+1}</text>`)});
 if(s.lure===c.k)out.push(`<circle cx="${x}" cy="${y-25}" r="17" fill="#ffe078" stroke="#f59d39" stroke-width="3"/><text class="tokenletter" x="${x}" y="${y-19}">F</text>`);
 if(s.alien===c.k)out.push(`<circle class="token" cx="${x+27}" cy="${y-25}" r="14" fill="#f27db6"/><text class="tokenletter" x="${x+27}" y="${y-19}">A</text>`);out.push('</g>')}out.push('</svg>');return out.join('')}
function buttons(){let p=me(),t=tile(p.pos),sel=tile(ui.selected),b=[];const add=(name,act,disabled=false,wide=false,cl='')=>b.push(`<button class="${wide?'wide ':''}${cl}" data-act="${act}" ${disabled||s.ap<1?'disabled':''}>${name}</button>`);
 if(p.captive){add('Escape the nest','escape');b.push('<button class="wide ghost" data-act="end">End turn</button>');return b.join('')}
 if(t.site?.status==='hidden')add(t.site.kind==='cargo'?'Search cargo':'Search signal','search',t.site.kind==='cargo'&&p.cargo.length>=2);
 if((t.site?.status==='found'||t.groundScientists)&&!p.scientist)add('Escort scientist','escort');if(p.scientist&&p.pos===SHUTTLE)add('Deliver scientist','deliver');
 s.players.forEach((other,i)=>{if(other.captive&&dist(p.pos,NEST)<=1)add(`Free ${esc(other.name)}`,`free:${i}`)});
 if(t.loose.length&&p.cargo.length<2)t.loose.forEach((_,i)=>add(`Pick up cargo ${i+1}`,`collect:${i}`));
 add('Use item','itemPicker',false,true,'primary');b.push('<button class="wide" data-act="privateCargo">View cargo</button>');
 if(p.cargo.length){p.cargo.forEach((_,i)=>add(`Drop cargo ${i+1}`,`drop:${i}`));if(p.pos===HOME)p.cargo.forEach((_,i)=>add(`Incinerate cargo ${i+1}`,`burn:${i}`,false,false,'danger'))}
 if(sel?.terrain==='bridge'&&dist(p.pos,ui.selected)<=1)add('Collapse selected bridge','collapse',!canCollapse(ui.selected));
 if(s.scans>0)add(`Scan cargo (${s.scans})`,'scan',false,true);
 if(p.cargo.length)add('Pass or snatch cargo','transfer',false,true);
 b.push('<button class="wide quiet" data-act="privateActions">Private actions</button>');
 if(s.delivered===2&&p.pos===SHUTTLE)add('Call for launch','launch',false,true,'primary');
 b.push('<button class="wide ghost" data-act="end">End turn</button>');return b.join('')}
function extra(){let p=me(),out='';if(ui.scan){let choices=s.players.flatMap((o,i)=>o.pos===p.pos?o.cargo.map((_,j)=>`<button data-act="scan:${i}:${j}">${esc(o.name)} · cargo ${j+1}</button>`):[]);out+=`<div class="panel"><h3>Choose cargo to scan</h3><div class="stack">${choices.join('')||'No cargo here.'}</div></div>`}
 if(ui.transfer){let choices=s.players.flatMap((o,i)=>i===s.turn?[]:[...(o.pos===p.pos?p.cargo.map((_,j)=>`<button data-act="give:${i}:${j}">Give cargo ${j+1} to ${esc(o.name)}</button>`):[]),...(dist(o.pos,p.pos)<=1&&o.cargo.length&&p.cargo.length<2?[`<button data-act="steal:${i}">Snatch random cargo from ${esc(o.name)}</button>`]:[])]);out+=`<div class="panel"><h3>Pass or snatch</h3><div class="stack">${choices.join('')||'No valid transfer nearby.'}</div></div>`}return out}
function targetPanel(){if(!ui.mode)return buttons();let item=ui.mode==='itemTarget'?me().cargo[ui.itemIndex]:null;let label=ui.mode==='itemTarget'?`Use ${item?.toUpperCase()||'ITEM'}`:ui.mode==='decoy'?'Place distress signal':'Redirect alien';return `<div class="target-panel"><h3>${label}</h3><p>Tap a glowing hex to choose the target. Nothing happens until you confirm.</p><p class="notice">${ui.targetHex?`Target: ${ui.targetHex}`:'Choose a highlighted hex'}</p><div class="actions"><button class="primary" data-act="confirmTarget" ${!ui.targetHex?'disabled':''}>Confirm target</button><button data-act="cancelTarget">Cancel</button></div></div>`}
function privateOverlay(){let p=me(),kind=ui.privateKind||'cargo';let content='';if(kind==='briefing')content=`<h2>${esc(p.name)} · first briefing</h2><p>Role: <strong class="${p.role==='saboteur'?'egg':''}">${p.role.toUpperCase()}</strong></p><p>${p.role==='saboteur'?'Get the egg aboard or prevent the rescue by round nine.':'Rescue both scientists and keep the egg off the shuttle.'}</p><p>Your role will not be repeated on later turns.</p>`;
 if(kind==='cargo'||ui.privateResult)content+=`<h2>${esc(p.name)} · cargo</h2><div class="stack">${p.cargo.length?p.cargo.map((v,i)=>`<div class="notice">${i+1}. <strong>${esc(v.toUpperCase())}</strong></div>`).join(''):'<p>Empty</p>'}</div>${ui.privateResult?`<p class="egg">${esc(ui.privateResult)}</p>`:''}<p>To use equipment, choose <strong>Use item</strong> in Actions.</p>`;
 if(kind==='items'){let items=p.cargo.map((v,i)=>({v,i})).filter(x=>['flare','jetpack','scanner','medkit'].includes(x.v));content=`<h2>Use item</h2><p>Choose an item privately, then tap a glowing target hex on the board and confirm.</p><div class="stack">${items.length?items.map(({v,i})=>`<button data-act="chooseItem:${i}">${esc(v.toUpperCase())}</button>`).join(''):'<p>You have no usable items.</p>'}</div>`}
 if(kind==='actions')content=`<h2>Private actions</h2>${p.role==='saboteur'?`<p>These options are visible only to you. Effects resolve at round end without naming you.</p><div class="stack"><button data-act="jam" ${!s.ap||!s.scans?'disabled':''}>Disable one scan charge</button><button data-act="decoy" ${!s.ap||!s.decoys?'disabled':''}>Plant false distress signal (${s.decoys} left)</button><button data-act="redirect" ${!s.ap?'disabled':''}>Redirect the creature</button></div>`:'<p>No role-specific actions. Use the public Actions menu for crew tasks and equipment.</p>'}`;
 return `<div class="overlay"><div class="card private"><div class="private-content">${content}</div><button class="primary" data-act="closePrivate">Hide private view</button></div></div>`}
function render(){let root=document.getElementById('app');if(!s){root.innerHTML=`<main class="screen"><div class="card"><h1>LAST SHUTTLE</h1><p>Pass-and-play prototype for 4–6 people on one iPad. Rescue two scientists while keeping the alien egg off the shuttle.</p><h2>Players</h2><div id="names" class="stack">${[1,2,3,4].map(i=>`<div class="field"><span>${i}</span><input aria-label="Player ${i} name" value="${['Xenia','Zander','Emma','Jim'][i-1]}"></div>`).join('')}</div><div class="row"><button data-act="add">Add player</button><button class="primary" data-act="start">Start game</button></div><details class="rules"><summary>How to play</summary><p>Each turn has two moves and one action. Tap a neighbouring hex to move. An event tile ends movement on first entry. Roles are shown once, before each player's first move.</p><p>The alien moves two hexes at round end. On contact it drags a player to the nest. Escape or free an ally with an action.</p></details></div></main>`;bind();return}
 if(s.phase==='handoff'){let p=me(),first=!p.briefed;root.innerHTML=`<main class="screen"><div class="card"><h1>LAST SHUTTLE</h1><p class="score">Round ${s.round} of 9 · ${esc(p.name)}'s turn</p><p>Pass the iPad to ${esc(p.name)}.${first?' Others should look away for their one-time role briefing.':''}</p>${s.alert?`<p class="notice">${esc(s.alert)}</p>`:''}<button class="primary" data-act="${first?'reveal':'startTurn'}">${first?`I am ${esc(p.name)} · reveal role`:'Start turn'}</button></div></main>`;bind();return}
 if(s.phase==='over'){root.innerHTML=`<main class="screen"><div class="card"><h1>${s.winner==='crew'?'CREW ESCAPED':'SABOTEUR WINS'}</h1><p class="score">${esc(s.log[0])}</p><p>Saboteur: <strong>${esc(s.players.find(p=>p.role==='saboteur').name)}</strong>. Scientists delivered: ${s.delivered}/2. Egg ${s.eggDestroyed?'destroyed':'not destroyed'}.</p><button class="primary" data-act="reset">Play again</button><h3>Final events</h3><div class="log">${s.log.slice(0,12).map(x=>`<div>${esc(x)}</div>`).join('')}</div></div></main>`;bind();return}
 if(s.phase==='launch'){let waiting=s.players.map((p,i)=>({p,i})).filter(o=>o.p.pos===SHUTTLE&&!o.p.captive);root.innerHTML=`<main class="screen"><div class="card"><h1>FINAL DEPARTURE</h1><p>Both scientists are aboard. Discuss who boards. Return to the board to use remaining scans.</p><div class="choices">${waiting.map(({p,i})=>`<label><input class="boarding" type="checkbox" value="${i}" checked> ${esc(p.name)} · ${p.cargo.length} face-down cargo</label>`).join('')}</div><div class="row"><button class="primary" data-act="depart">Close hatch · reveal</button><button data-act="cancelLaunch">Back to board</button></div></div></main>`;bind();return}
 let p=me();root.innerHTML=`<header class="top"><h1>LAST SHUTTLE</h1><div class="meta"><span class="pill">Round <b>${s.round}/9</b></span><span class="pill">${esc(p.name)}</span><span class="pill">Moves <b>${s.moves}/2</b></span><span class="pill">Action <b>${s.ap?'ready':'used'}</b></span><span class="pill">Scientists <b>${s.delivered}/2</b></span><span class="pill">Scans <b>${s.scans}</b></span></div></header><main class="layout"><section class="board">${board()}</section><aside class="side"><div class="panel"><h2>Actions · ${esc(p.name)}</h2><p>Tap a neighbouring hex to move. Select an item or private action here, then choose a glowing target hex.</p>${p.captive?'<p class="notice">CAPTIVE AT THE NEST · Escape with an action or wait for an ally.</p>':''}${hexInfo(ui.selected)}${ui.note?`<p class="notice">${esc(ui.note)}</p>`:''}<div class="actions">${targetPanel()}</div></div>${extra()}<div class="panel"><h3>Recent events</h3><div class="log">${s.log.slice(0,8).map(x=>`<div>${esc(x)}</div>`).join('')}</div></div><details class="panel rules"><summary>Rules and terrain</summary><p>Two moves and one action, in any order. Event tiles end movement on first entry, then become open ground. Bridges can collapse. Matching tunnels connect in one move. Cover hides from nearest-target selection unless you make noise. Spores create noise.</p><p>The alien moves two hexes at round end towards a flare, recent noise, or the nearest visible player. Contact sends a player to the nest. Their scientist drops where caught; one random cargo drops at the nest. Escape with an action, or an ally beside the nest can free them.</p><p>◆ cargo · ! distress · ✚ scientist · A alien. Crew must launch both scientists without the egg. The saboteur wins if the egg boards or round nine ends.</p></details></main><div class="footer">The current game saves on this device · shield the iPad when viewing private controls</div>`;
 if(ui.private||ui.privateResult)root.innerHTML+=privateOverlay();
 if(s.pendingEvent){let msg=s.pendingEvent==='Risky salvage'?'Take a jetpack, but the alien moves one hex toward you?':'Reveal one distress signal, but spend one scan charge if available?';root.innerHTML+=`<div class="overlay"><div class="card"><h2>EVENT CHOICE</h2><p>${msg}</p><div class="row"><button class="primary" data-act="eventYes">Take the risk</button><button data-act="eventNo">Leave it</button></div></div></div>`}
 bind()}
function bind(){document.querySelectorAll('[data-hex]').forEach(el=>el.addEventListener('click',()=>{let k=el.dataset.hex;if(s.phase!=='play'||s.pendingEvent)return;if(ui.mode){if(targetValid(k)){ui.targetHex=k;ui.note=`Target ${k} selected. Confirm or cancel.`}else ui.note='Choose a glowing valid hex.';render();return}let p=me(),pair=tile(p.pos).terrain==='tunnel'&&tile(k).terrain==='tunnel'&&tile(k).known&&tile(p.pos).pair===tile(k).pair&&k!==p.pos;if(s.moves>0&&!p.captive&&(dist(p.pos,k)===1||pair)){move(k);return}ui.selected=k;render()}));document.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',()=>act(el.dataset.act)))}
function act(a){if(a==='add'){let n=document.querySelectorAll('#names input').length;if(n>=6)return;document.querySelector('#names').insertAdjacentHTML('beforeend',`<div class="field"><span>${n+1}</span><input aria-label="Player ${n+1} name" value="Player ${n+1}"></div>`);return}
 if(a==='start'){let names=[...document.querySelectorAll('#names input')].map(x=>x.value.trim()).filter(Boolean);if(names.length<4)return alert('Add at least four player names.');newGame(names);return}if(a==='reset'){if(confirm('Start a new game?')){localStorage.removeItem(KEY);s=null;render()}return}
 if(a==='reveal'){s.phase='play';me().briefed=true;ui.private=true;ui.privateKind='briefing';finish();return}if(a==='startTurn'){s.phase='play';ui.private=false;ui.privateKind='';finish();return}
 if(a==='closePrivate'){ui.private=false;ui.privateKind='';ui.privateResult='';render();return}
 if(a==='privateCargo'){ui.private=true;ui.privateKind='cargo';render();return}if(a==='privateActions'){ui.private=true;ui.privateKind='actions';render();return}if(a==='itemPicker'){if(s.ap<1||me().captive)return;ui.private=true;ui.privateKind='items';render();return}
 if(a==='eventYes'||a==='eventNo'){chooseEvent(a==='eventYes');return}if(a==='cancelLaunch'){s.phase='play';finish();return}if(a==='depart'){finishLaunch();return}if(a==='end'){endTurn();return}
 if(s.pendingEvent)return;
 if(a==='confirmTarget'){if(!ui.targetHex)return;if(ui.mode==='itemTarget')return useItem();if(ui.mode==='decoy')return plant(ui.targetHex);if(ui.mode==='redirect')return redirect(ui.targetHex)}
 if(a==='cancelTarget'){cancelTarget();return}
 if(a==='jam'){jamScan();return}if(a==='decoy'){if(me().role!=='saboteur')return;ui.private=false;ui.privateKind='';ui.mode='decoy';ui.targetHex=null;return notice('Choose an adjacent hex for a false signal, then confirm.')}if(a==='redirect'){if(me().role!=='saboteur')return;ui.private=false;ui.privateKind='';ui.mode='redirect';ui.targetHex=null;return notice('Choose a hex within two spaces, then confirm.')}
 if(a==='search')return search();if(a==='escort')return escort();if(a==='deliver')return deliver();if(a==='escape')return escapeNest();if(a==='collapse')return collapse(ui.selected);if(a==='scan'){ui.scan=!ui.scan;ui.transfer=false;render();return}if(a==='transfer'){ui.transfer=!ui.transfer;ui.scan=false;render();return}if(a==='launch')return launch();
 let [type,x,y]=a.split(':');if(type==='chooseItem')return beginItem(+x);if(type==='free')return freeCaptive(+x);if(type==='collect')return collect(+x);if(type==='drop')return drop(+x);if(type==='burn')return incinerate(+x);if(type==='scan')return scan(+x,+y);if(type==='give')return transfer(+x,+y,false);if(type==='steal')return transfer(+x,0,true)}
 render();
})();
