const assert=require('node:assert/strict'),{harness}=require('./audit-harness'),fs=require('node:fs'),path=require('node:path');
const h=harness(),t=h.t;t.ui.boot='roster';t.ui.roster=[{name:'',voice:'female'},{name:'',voice:'male'},{name:'',voice:'female'},{name:'',voice:'male'}];t.ui.nameEdit=0;
const fields=t.ui.roster.map(()=>({value:'',classList:{toggle(){}}})),readout={textContent:''},heading={textContent:''},shift={textContent:'',setAttribute(){}},voice={dataset:{voice:'male'},setAttribute(){}},keys=Array.from('QWERTYUIOP',(k,i)=>({dataset:{act:'nameKey:1:'+i},textContent:k}));
const keyboard={querySelector:s=>s==='[data-keyboard-name]'?readout:s==='header > span'?heading:shift,querySelectorAll:()=>keys,remove(){this.removed=true}};
h.context.document.querySelector=s=>s==='.crt-keyboard'?keyboard:s.includes('toggleVoice')?voice:null;h.context.document.querySelectorAll=s=>s==='#names input'?fields:[];
const before=h.renders.length;for(const a of ['nameChar:J','nameChar:i','nameChar:m','nameBackspace','nameShift','nameKey:1:0'])t.rosterAction(a);assert.equal(t.ui.roster[0].name,'Jiq');assert.equal(fields[0].value,'Jiq');assert.equal(readout.textContent,'Jiq');assert.equal(keys[0].textContent,'q');
t.rosterAction('nameNext');t.rosterAction('nameChar:E');assert.equal(readout.textContent,'E');assert.equal(fields[1].value,'E');t.rosterAction('toggleVoice:1');assert.equal(voice.dataset.voice,'female');assert.equal(voice.textContent,'VOICE: FEMALE');assert.equal(h.renders.length,before,'Keyboard actions must not rebuild the roster');t.rosterAction('nameDone');assert.ok(keyboard.removed);assert.equal(h.renders.length,before);
const manual=t.fieldManual();assert.equal((manual.match(/class="manual-tile"/g)||[]).length,15);for(const text of ['Weyland-Yutani','nine hours','automatically boards','zero hours','permanently reveals','CLOSE MANUAL'])assert.ok(manual.includes(text),text);const wrist=fs.readFileSync(path.join(__dirname,'../wrist-terminal.js'),'utf8');assert.ok(wrist.includes('if(ui.rules){cancel();return}'));assert.ok(!wrist.includes("const selectors=['.rules-window'"));
console.log('PASS: in-place name/case/Next/voice updates and Done removal without roster renders; full manual story, tile key, current extraction/flare rules and no wrist wrapping.');
