const {harness}=require('./audit-harness'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createCanvas,loadImage}=require('@napi-rs/canvas');
const settle=async()=>{for(let i=0;i<16;i++)await Promise.resolve()};
(async()=>{
// Boarding must be an explicit user decision; arrival leaves movement available.
const h=harness({realFinish:true}),t=h.t,p=t.s.players[0];p.pos='2,-2';p.scientist=false;t.s.alien=t.s.nest;t.arrive(t.DROPSHIP,'moved');assert.ok(!t.ui.messages?.some(m=>m.kind==='boarding'));assert.ok(!t.ui.popup);t.act('boardDropship');await settle();assert.equal(t.ui.popup?.kind,'boarding');const popup=t.popupMarkup();assert.ok(popup.includes('data-terminal-label="CANCEL"'));assert.ok(popup.includes('data-close-audio="true"'));t.closePopup();await settle();assert.equal(p.boarded,false);assert.equal(t.ui.sequence,false);t.act('boardDropship');await settle();t.act('confirmBoarding');await settle();h.advance(450);await settle();assert.equal(p.boarded,true);
// Diagnostic handler remains usable with normal gameplay blocked; error logging is independent.
const d=harness({diagnostics:true}),dt=d.t;dt.bind();dt.ui.sequence=true;dt.ui.capturePrelude=true;const target={closest:key=>key==='[data-diagnostic]'?target:null};for(const fn of d.listeners.pointerup||[])fn({target,preventDefault(){},stopImmediatePropagation(){}});const panel=d.context.document.body.children.find(n=>n.className==='diagnostic-panel crt');assert.ok(panel);assert.ok(panel.querySelector('pre').textContent.includes('Input blocked by: sequence'));assert.equal(dt.ui.sequence,true,'diagnostic does not unlock active game sequences');d.listeners['window:error'][0]({error:new Error('Simulated render exception')});assert.equal(d.context.window.ShipInputDiagnostics().errors.at(-1).message,'Simulated render exception');assert.ok(d.context.document.body.children[0].querySelector('small').textContent.includes('ERR'));
// Shared CRT must retain the Cancel label rather than relabel every footer.
const wrist=fs.readFileSync(path.join(__dirname,'../wrist-terminal.js'),'utf8');assert.ok(wrist.includes("ack.dataset.terminalLabel||'ACKNOWLEDGE'"));
// Actual canvas: green storm light illuminates revealed terrain and surround, preserves fog.
let thunder=0;const source=fs.readFileSync(path.join(__dirname,'../terrain.js'),'utf8').replace('window.ShipTerrain={mount,','window.ShipTerrain={drawStormFlash,drawWeather,weatherFor,mount,');const c={window:{ShipStormThunder:()=>thunder++},document:{addEventListener(){}},performance:{now:()=>0},console};vm.runInNewContext(source,c);const api=c.window.ShipTerrain,game={tiles:{'0,0':{known:false},'1,0':{known:true}}},cells=[{k:'0,0'},{k:'1,0'}],centre=k=>k==='0,0'?[200,220]:[400,220];
const canvas=createCanvas(820,614),ctx=canvas.getContext('2d');ctx.fillStyle='#101010';ctx.fillRect(0,0,820,614);api.drawStormFlash(ctx,{strike:0,bolt:[[760,20],[770,100]],game},100,false,cells,centre,[0,0,820,614]);const pix=(x,y)=>Array.from(ctx.getImageData(x,y,1,1).data);assert.deepEqual(pix(180,212),[16,16,16,255]);assert.ok(pix(380,212)[1]>pix(380,212)[0]);assert.ok(pix(50,50)[1]>40);
const weather={next:Infinity,strike:0,thunderDue:900,bolt:[]};api.drawWeather(ctx,weather,899,false,cells,centre,[0,0,820,614],game);assert.equal(thunder,0);api.drawWeather(ctx,weather,900,false,cells,centre,[0,0,820,614],game);api.drawWeather(ctx,weather,1200,false,cells,centre,[0,0,820,614],game);assert.equal(thunder,1);weather.thunderDue=1300;api.drawWeather(ctx,weather,1300,true,cells,centre,[0,0,820,614],game);assert.equal(thunder,1);
const f=api.foreground(game,cells,centre,'1,0');assert.ok(f.includes('dropship-ramp'));assert.ok(f.includes('Port red'));assert.ok(f.includes('Starboard green'));assert.ok(!f.includes('staging-hazards'));
for(const name of ['alien-body.webp','alien-tail.webp','flare-overhead.webp','dropship-landing.webp'])await loadImage(path.join(__dirname,'../',name));
t.s.players[0].pos='0,0';t.s.players[0].boarded=false;t.s.alien='1,0';t.s.tiles['1,0'].known=true;t.ui.alienMotion=null;assert.ok(t.alienIcon().includes('alien-idle'));t.ui.alienMotion={from:'1,0',to:'0,0',started:0,duration:1000,oldFacing:0};assert.ok(t.alienIcon().includes('alien-scuttling'));assert.ok(t.flareIcon({hex:'0,0'}).includes('flare-overhead.webp'));
console.log('PASS: explicit boarding and Cancel, confirmation/turn continuation, independent freeze diagnostics/errors, bright green storm without fog reveal, delayed once-only thunder, ship ramp/nav layering, decoded sprites and alien animation.');
})().catch(e=>{console.error(e);process.exitCode=1});
