const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),{createCanvas,loadImage}=require('@napi-rs/canvas'),{harness}=require('./audit-harness');
(async()=>{const root=path.resolve(__dirname,'..'),src=fs.readFileSync(root+'/terrain.js','utf8'),sources=JSON.parse(src.match(/const SOURCES=(.*?),images=new Map/)[1]),loaded={};for(const [name,uri] of Object.entries(sources))loaded[name]=await loadImage(Buffer.from(uri.split(',')[1],'base64'));loaded.valley=await loadImage(root+'/board-valley.webp');
const c={window:{},loaded,Image:function(){},document:{hidden:false,createElement:()=>createCanvas(820,614),addEventListener(){}},performance:{now:()=>100},requestAnimationFrame:()=>1,cancelAnimationFrame(){},console};vm.runInNewContext(src.replace(/function image\(name,redraw\)\{.*?\n/,'function image(name){return loaded[name]}\n'),c);
const h=harness(),t=h.t;h.context.window.ShipTerrain=c.window.ShipTerrain;vm.runInNewContext(fs.readFileSync(root+'/artwork.js','utf8'),h.context);for(const tile of Object.values(t.s.tiles))tile.known=true;t.s.players[0].pos='1,0';t.s.players[1].pos='-1,1';t.s.players[2].pos='2,-1';t.s.players[3].pos='-1,-1';t.s.flares=[{hex:'1,1'}];t.s.alien='0,1';t.ui.revealing={};t.s.sentries=[{hex:'1,0',armed:true,deployFacing:0,aim:0,firingUntil:0}];t.s.tiles['1,0'].emplacement=true;
const cells=Object.keys(t.s.tiles).map(k=>({k})),centre=k=>{const[q,r]=k.split(',').map(Number);return[360+Math.sqrt(3)*55*(q+r/2),315+82.5*r]},canvas=createCanvas(820,614);canvas.isConnected=true;c.window.ShipTerrain.mount(canvas,t.s,cells,centre,t.DROPSHIP,()=>{},t.marineFacing);
const ctx=canvas.getContext('2d');
// Native canvas composite of the production token sizes/transforms; no browser is installed.
for(const cell of cells){const [cx,cy]=centre(cell.k),x=cx-20,y=cy-8;ctx.beginPath();for(let i=0;i<6;i++){const a=(60*i-30)*Math.PI/180;ctx.lineTo(x+55*Math.cos(a),y+55*Math.sin(a))}ctx.closePath();ctx.strokeStyle='#526c59aa';ctx.lineWidth=1.05;ctx.stroke()}
const foreground=c.window.ShipTerrain.foreground(t.s,cells,centre,t.DROPSHIP),ramp=foreground.match(/polygon points="([^"]+)"/)[1].split(' ').map(p=>p.split(',').map(Number)),[sx,sy]=centre(t.DROPSHIP),shipX=sx-320*.19,shipY=sy-665*.19;
ctx.save();ctx.beginPath();ramp.forEach(([x,y],i)=>i?ctx.lineTo(x-20,y-8):ctx.moveTo(x-20,y-8));ctx.closePath();ctx.clip();ctx.globalAlpha=.73;ctx.drawImage(loaded.landing,shipX-20,shipY-8,1536*.19,1024*.19);ctx.restore();
for(const [dx,dy,col] of [[1300,208,'#ff353b'],[858,752,'#3dff8b']]){const x=shipX+dx*.19-20,y=shipY+dy*.19-8,g=ctx.createRadialGradient(x,y,0,x,y,13);g.addColorStop(0,col+'99');g.addColorStop(1,col+'00');ctx.fillStyle=g;ctx.fillRect(x-13,y-13,26,26);ctx.fillStyle=col;ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill()}
const marine=await loadImage(root+'/marine-tokens.png');t.s.players.forEach((p,i)=>{const [x,y]=centre(p.pos),gun=t.s.sentries.find(g=>g.hex===p.pos),a=(gun?.deployFacing||0)*Math.PI/180;ctx.save();ctx.translate(x-20-(gun?Math.sin(a)*18:0),y-8+(gun?Math.cos(a)*18:0));ctx.rotate((t.marineFacing(p,i).angle-180)*Math.PI/180);ctx.drawImage(marine,i*543,0,543,724,-18.4,-23,36.8,46);ctx.restore()});
const parts=await loadImage(root+'/sentry-overhead-parts.png');for(const gun of t.s.sentries){const [x,y]=t.sentryCentre(gun);ctx.save();ctx.translate(x-20,y-8);ctx.scale(.55,.55);ctx.drawImage(parts,0,0,920,900,-31.36,-39.2,64.4,63);ctx.rotate(t.sentryAim(gun)*Math.PI/180);ctx.drawImage(parts,1000,0,480,1000,-21,-55.125,36,75);ctx.fillStyle='#ff3223';ctx.beginPath();ctx.arc(10.425,-6.375,1.2,0,Math.PI*2);ctx.fill();ctx.restore()}
const flare=await loadImage(root+'/flare-overhead.webp');for(const f of t.s.flares){const[x,y]=centre(f.hex);ctx.drawImage(flare,x-29,y-23,24,16)}
const [ax,ay]=centre(t.s.alien);ctx.save();ctx.translate(ax+4,ay-30);ctx.rotate(t.alienFacing()*Math.PI/180);for(const name of ['alien-body.webp','alien-tail.webp'])ctx.drawImage(await loadImage(root+'/'+name),-23,-29,46,60);ctx.restore();
fs.writeFileSync(root+'/verification/v97-board.png',canvas.toBuffer('image/png'));c.window.ShipTerrain.stop();console.log('PASS: native canvas terrain + production-scale sprite composite renders new flare, alien body/tail and foreground ramp/navigation lights (browser animation not evaluated).');})().catch(e=>{console.error(e);process.exitCode=1});
