const {harness}=require('./audit-harness'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createCanvas}=require('@napi-rs/canvas');
const settle=async()=>{for(let i=0;i<20;i++)await Promise.resolve()};
(async()=>{
 const h=harness(),t=h.t;h.context.window.ShipTerrain={foreground:()=>'',stop(){}};
 // Deployment offsets the gun ahead and places the Marine behind, on one legal tile.
 t.s.players[0].pos='1,0';t.s.players[0].facing=90;t.s.alien='-3,0';t.s.players[0].cargo=['sentry'];t.beginItem(0);t.act('confirmTarget');const gun=t.s.sentries[0];assert.equal(gun.deployFacing,90);assert.ok(t.sentryIcon(gun).includes('scale(.55)'));const [gx,gy]=t.sentryCentre(gun);assert.ok(gx>450);assert.equal(gy,315);const board=t.board();assert.ok(board.includes('sentry-piece'));assert.equal(t.s.players[0].pos,'1,0');assert.equal(t.s.moves,2);assert.equal(t.s.ap,1);
 // Actual roster renderer mounts the renamed manual without losing entered names.
 t.ui.boot='roster';t.ui.roster=[{name:'Saved Marine',voice:'male'}];t.ui.rules=true;t.renderContent();const roster=h.context.document.getElementById('app').innerHTML;assert.ok(roster.includes('Saved Marine'));assert.ok(roster.includes('data-act="openRules">FIELD MANUAL'));assert.ok(roster.includes('id="rules-title">FIELD MANUAL'));assert.ok(!roster.includes('HOW TO PLAY'));
 const manual=t.fieldManual();for(const phrase of ['three tiles','Seismic Shift','Confirm Boarding','translucent red','0.65 seconds','Three overlapping','undiscovered tile','Missing the nine-hour launch window fails the mission'])assert.ok(manual.includes(phrase),phrase);
 // Triple-burst is requested once as popup opens, so each layer cannot cancel another.
 h.fresh();h.calls.length=0;t.s.events=['Spore burst'];t.triggerEvent(t.HOME);await settle();assert.equal(h.calls.filter(k=>k==='sporeBurst').length,1);assert.equal(t.s.moves,0);assert.ok(t.popupMarkup().includes('Spore burst'));t.closePopup();await settle();h.advance(2000);await settle();assert.equal(h.calls.filter(k=>k==='sporeBurst').length,1);
 // Native canvas corner lighting: green body / near-white centre, random corners, no fog reveal.
 const source=fs.readFileSync(path.join(__dirname,'../terrain.js'),'utf8').replace('window.ShipTerrain={mount,','window.ShipTerrain={drawStormFlash,drawWeather,mount,');let thunder=0;const c={window:{ShipStormThunder:()=>thunder++},document:{addEventListener(){}},console};let randomIndex=0;c.Math=Object.create(Math);c.Math.random=()=>[0,.45,.85][randomIndex++%3];vm.runInNewContext(source,c);const api=c.window.ShipTerrain,game={tiles:{hidden:{known:false},seen:{known:true}}},cells=[{k:'hidden'},{k:'seen'}],centre=k=>k==='hidden'?[120,128]:[350,308];
 const bright=[];for(let corner=0;corner<4;corner++){const canvas=createCanvas(820,614),ctx=canvas.getContext('2d');ctx.fillStyle='#101010';ctx.fillRect(0,0,820,614);api.drawStormFlash(ctx,{strike:0,corner,game},0,false,cells,centre,[0,0,820,614]);const sample=(x,y)=>Array.from(ctx.getImageData(x,y,1,1).data);assert.deepEqual(sample(100,120),[16,16,16,255]);const points=[[49,37],[771,37],[49,577],[771,577]],values=points.map(([x,y])=>sample(x,y)[1]);assert.equal(values.indexOf(Math.max(...values)),corner);assert.ok(sample(...points[corner])[1]>120);bright.push(values)}
 const state={strike:-Infinity,corner:null,next:0,thunderDue:Infinity,game},ctx=createCanvas(820,614).getContext('2d');let previous=null;const corners=new Set();for(let i=0;i<20;i++){state.next=i*2000;api.drawWeather(ctx,state,i*2000,false,cells,centre,[0,0,820,614],game);assert.notEqual(state.corner,previous);corners.add(state.corner);previous=state.corner}assert.equal(corners.size,4);
 console.log('PASS: smaller forward sentry without movement/action changes, actual roster/manual render and saved names, one triple-spore request per opening, four randomized green-white flash corners and unrevealed-tile masking.');
})().catch(e=>{console.error(e);process.exitCode=1});
