const {harness}=require('./audit-harness'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
(async()=>{
for(const voice of ['male','female'])for(const anomaly of [false,true]){
 const h=harness({realFinish:true}),t=h.t,p=t.s.players[1];p.voice=voice;p.impregnated=anomaly;p.cargo=['flare','egg'];t.s.ap=1;t.s.scans=2;t.scan(1);
 assert.equal(t.s.ap,0);assert.equal(t.s.scans,1);assert.equal(t.ui.popup.kind,'bioscan');assert.equal(t.ui.popup.anomaly,anomaly);assert.ok(h.calls.includes('discovery'));
 const html=t.popupMarkup();assert.ok(html.includes(voice==='female'?'Female body scan':'Male body scan'));assert.ok(html.includes('FLARE')&&html.includes('EGG'));assert.equal(html.includes('bioscan-mass'),anomaly);assert.equal(html.includes('ANOMALY DETECTED'),anomaly);assert.ok(!html.includes('impregnated'));assert.ok(html.includes('ACKNOWLEDGE'));
 t.closePopup();for(let i=0;i<12;i++)await Promise.resolve();assert.equal(t.ui.sequence,false);assert.equal(t.ui.popup,null);
 assert.deepEqual(Array.from(t.knownInventory(1)),['flare','egg']);t.s.turn=2;assert.equal(t.knownInventory(1),null);t.s.turn=0;p.cargo.pop();t.invalidateScanKnowledge();assert.equal(t.knownInventory(1),null);
}
for(const condition of ['distant','boarded','captive','nocharge','noaction']){const {t}=harness();const p=t.s.players[1];if(condition==='distant')p.pos='2,0';if(condition==='boarded')p.boarded=true;if(condition==='captive')p.captive=true;if(condition==='nocharge')t.s.scans=0;if(condition==='noaction')t.s.ap=0;const ap=t.s.ap,charges=t.s.scans;t.scan(1);assert.equal(t.s.ap,ap);assert.equal(t.s.scans,charges);assert.equal((t.ui.messages||[]).length,0)}
{const {t}=harness();t.s.players[1].cargo=[];t.scan(1);assert.equal(t.s.scans,1);assert.equal(t.ui.messages[0].items.length,0)}
{const {t}=harness();t.ui.transfer=true;t.s.players[0].cargo=['flare'];t.s.players[1].cargo=['egg'];let html=t.extra();assert.ok(html.includes('Pass FLARE to B'));assert.ok(html.includes('Take Inventory 1 from B'));assert.ok(!html.includes('Take EGG'));t.s.scanKnowledge={0:{1:{signature:JSON.stringify(['egg']),items:['egg']}}};assert.ok(t.extra().includes('Take EGG from B'));t.transfer(1,0,true);assert.deepEqual(Array.from(t.s.players[0].cargo),['flare','egg']);assert.equal(t.s.players[1].cargo.length,0);assert.equal(t.s.ap,0)}
{const {t}=harness();t.s.players[0].cargo=[];t.s.players[1].cargo=['flare','egg'];assert.ok(t.buttons().includes('Pass or take equipment'));t.transfer(1,1,true);assert.deepEqual(Array.from(t.s.players[0].cargo),['egg']);assert.deepEqual(Array.from(t.s.players[1].cargo),['flare'])}
const source=fs.readFileSync(path.join(__dirname,'../terrain.js'),'utf8'),context={window:{},performance:{now:()=>1000},document:{},Image:class{},cancelAnimationFrame(){}};vm.runInNewContext(source,context);const game={round:7,tiles:{},players:[]},render=()=>context.window.ShipTerrain.foreground(game,[],()=>[0,0],'2,-2');assert.ok(!render().includes('ship-amber-beacon'));game.shipBeaconActive=true;assert.ok(render().includes('ship-amber-beacon'));assert.ok(render().includes('dur="3.6s"'));assert.ok(source.includes("[1261,168,'#ff353b'"));assert.ok(source.includes("[849,688,'#3dff8b'"));
const code=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');assert.ok(code.includes('s.round++;if(s.round===8)s.shipBeaconActive=true;startNext'));const css=fs.readFileSync(path.join(__dirname,'../style.css'),'utf8');assert.ok(css.includes('pointer-events:none;z-index:4'));assert.ok(css.includes('prefers-reduced-motion:reduce'));
console.log('PASS: male/female clear/anomaly whole-person scans, sound, one charge/action, ACK releases input, private inventory knowledge and expiry, blind/named selected-slot transfers, amber beacon gating, marked navigation lights, decorative CRT overlays.');
})().catch(e=>{console.error(e);process.exitCode=1});
